spring:

#  cloud:
#    config:
#      enabled: false
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

  #  config:
#    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  application:
    name: IoTMining-Gateway-Service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
server:
  port: 8057

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true  # Use IP instead of hostname for discovery

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty: INFO
#

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server: DEBUG
